// Baseline Cloudflare bindings for the Next.js worker.
//
// NOTE: deliberately NOT `/// <reference types="@cloudflare/workers-types" />`
// here — that override clobbers the DOM `Response.json()` typing across the
// whole app. Precise binding types are regenerated by `npm run cf-typegen`
// (run inside the Cloudflare toolchain), which emits a self-contained
// worker-configuration.d.ts. Until bindings are actually consumed via
// getCloudflareContext(), the loose shapes below are sufficient.
interface CloudflareEnv {
  ASSETS: unknown
  WORKER_SELF_REFERENCE: unknown
  NEXT_INC_CACHE_R2_BUCKET: unknown
  IMAGES: unknown
  AI: { run(model: string, inputs: unknown): Promise<unknown> }

  // Vars / secrets (set via wrangler.jsonc vars or `wrangler secret put`)
  NEXT_PUBLIC_SITE_URL: string
  MONGODB_URI: string
  BETTER_AUTH_SECRET: string
  BETTER_AUTH_URL: string
  GEMINI_API_KEY: string
  GEMINI_MODEL: string
  PADDLE_API_KEY: string
  PADDLE_WEBHOOK_SECRET: string
  NEXT_PUBLIC_PADDLE_CLIENT_TOKEN: string
  PADDLE_ENV: string
  CRON_SECRET: string
  RESEND_API_KEY: string
}
