// Baseline Cloudflare bindings for the Next.js worker.
//
// NOTE: deliberately NOT `/// <reference types="@cloudflare/workers-types" />`
// here — that override clobbers the DOM `Response.json()` typing across the
// whole app. Precise binding types are regenerated by `npm run cf-typegen`
// (run inside the Cloudflare toolchain), which emits a self-contained
// worker-configuration.d.ts. Until bindings are actually consumed via
// getCloudflareContext(), the loose shapes below are sufficient.
interface CloudflareEnv {
  ASSETS: unknown
  WORKER_SELF_REFERENCE: unknown
  NEXT_INC_CACHE_R2_BUCKET: unknown
  IMAGES: unknown
  AI: { run(model: string, inputs: unknown): Promise<unknown> }
  RATE_LIMIT_KV: {
    get(key: string): Promise<string | null>
    put(
      key: string,
      value: string,
      options?: { expirationTtl?: number }
    ): Promise<void>
  }

  // Vars / secrets (set via wrangler.jsonc vars or `wrangler secret put`)
  NEXT_PUBLIC_SITE_URL: string
  DATABASE_URL: string
  AUTH0_DOMAIN: string
  AUTH0_CLIENT_ID: string
  AUTH0_CLIENT_SECRET: string
  AUTH0_SECRET: string
  APP_BASE_URL: string
  BETTER_AUTH_SECRET: string
  BETTER_AUTH_URL: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  APPLE_CLIENT_ID: string
  APPLE_CLIENT_SECRET: string
  GEMINI_API_KEY: string
  GEMINI_MODEL: string
  BILLING_PROVIDER: string
  REVENUECAT_SECRET_KEY: string
  REVENUECAT_WEBHOOK_SECRET: string
  STORE_PRODUCT_EXPLORER: string
  STORE_PRODUCT_COMPLETE: string
  STORE_PRODUCT_PRACTITIONER: string
  STORE_PRODUCT_LIFETIME: string
  CRON_SECRET: string
  UNSUBSCRIBE_SECRET: string
  RESEND_API_KEY: string
}
