services:
  - type: worker
    name: omnis-scraper
    runtime: docker
    dockerfilePath: ./Dockerfile.scraper
    plan: starter
    region: oregon
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SCRAPER_MAX_PAGES
        value: "500"
