// AUTO-GENERATED by scripts/generate-glyphs.mjs — DO NOT EDIT.
// Source: assets/glyphs/** (potrace monochrome, fill="currentColor").
// Regenerate: node scripts/generate-glyphs.mjs
import type React from 'react'
import type { SvgProps } from 'react-native-svg'
import SEAL_01_dragon from './dreamspell/seals/01-dragon.svg'
import SEAL_02_wind from './dreamspell/seals/02-wind.svg'
import SEAL_03_night from './dreamspell/seals/03-night.svg'
import SEAL_04_seed from './dreamspell/seals/04-seed.svg'
import SEAL_05_serpent from './dreamspell/seals/05-serpent.svg'
import SEAL_06_worldbridger from './dreamspell/seals/06-worldbridger.svg'
import SEAL_07_hand from './dreamspell/seals/07-hand.svg'
import SEAL_08_star from './dreamspell/seals/08-star.svg'
import SEAL_09_moon from './dreamspell/seals/09-moon.svg'
import SEAL_10_dog from './dreamspell/seals/10-dog.svg'
import SEAL_11_monkey from './dreamspell/seals/11-monkey.svg'
import SEAL_12_human from './dreamspell/seals/12-human.svg'
import SEAL_13_skywalker from './dreamspell/seals/13-skywalker.svg'
import SEAL_14_wizard from './dreamspell/seals/14-wizard.svg'
import SEAL_15_eagle from './dreamspell/seals/15-eagle.svg'
import SEAL_16_warrior from './dreamspell/seals/16-warrior.svg'
import SEAL_17_earth from './dreamspell/seals/17-earth.svg'
import SEAL_18_mirror from './dreamspell/seals/18-mirror.svg'
import SEAL_19_storm from './dreamspell/seals/19-storm.svg'
import SEAL_20_sun from './dreamspell/seals/20-sun.svg'
import TONE_01_magnetic from './dreamspell/tones/01-magnetic.svg'
import TONE_02_lunar from './dreamspell/tones/02-lunar.svg'
import TONE_03_electric from './dreamspell/tones/03-electric.svg'
import TONE_04_self_existing from './dreamspell/tones/04-self-existing.svg'
import TONE_05_overtone from './dreamspell/tones/05-overtone.svg'
import TONE_06_rhythmic from './dreamspell/tones/06-rhythmic.svg'
import TONE_07_resonant from './dreamspell/tones/07-resonant.svg'
import TONE_08_galactic from './dreamspell/tones/08-galactic.svg'
import TONE_09_solar from './dreamspell/tones/09-solar.svg'
import TONE_10_planetary from './dreamspell/tones/10-planetary.svg'
import TONE_11_spectral from './dreamspell/tones/11-spectral.svg'
import TONE_12_crystal from './dreamspell/tones/12-crystal.svg'
import TONE_13_cosmic from './dreamspell/tones/13-cosmic.svg'
import SIGN_01_aries from './astrology/signs/01-aries.svg'
import SIGN_02_taurus from './astrology/signs/02-taurus.svg'
import SIGN_03_gemini from './astrology/signs/03-gemini.svg'
import SIGN_04_cancer from './astrology/signs/04-cancer.svg'
import SIGN_05_leo from './astrology/signs/05-leo.svg'
import SIGN_06_virgo from './astrology/signs/06-virgo.svg'
import SIGN_07_libra from './astrology/signs/07-libra.svg'
import SIGN_08_scorpio from './astrology/signs/08-scorpio.svg'
import SIGN_09_sagittarius from './astrology/signs/09-sagittarius.svg'
import SIGN_10_capricorn from './astrology/signs/10-capricorn.svg'
import SIGN_11_aquarius from './astrology/signs/11-aquarius.svg'
import SIGN_12_pisces from './astrology/signs/12-pisces.svg'
import LETTER_01_aleph from './gematria/letters/01-aleph.svg'
import LETTER_02_bet from './gematria/letters/02-bet.svg'
import LETTER_03_gimel from './gematria/letters/03-gimel.svg'
import LETTER_04_dalet from './gematria/letters/04-dalet.svg'
import LETTER_05_he from './gematria/letters/05-he.svg'
import LETTER_06_vav from './gematria/letters/06-vav.svg'
import LETTER_07_zayin from './gematria/letters/07-zayin.svg'
import LETTER_08_chet from './gematria/letters/08-chet.svg'
import LETTER_09_tet from './gematria/letters/09-tet.svg'
import LETTER_10_yod from './gematria/letters/10-yod.svg'
import LETTER_11_kaf from './gematria/letters/11-kaf.svg'
import LETTER_12_lamed from './gematria/letters/12-lamed.svg'
import LETTER_13_mem from './gematria/letters/13-mem.svg'
import LETTER_14_nun from './gematria/letters/14-nun.svg'
import LETTER_15_samech from './gematria/letters/15-samech.svg'
import LETTER_16_ayin from './gematria/letters/16-ayin.svg'
import LETTER_17_pe from './gematria/letters/17-pe.svg'
import LETTER_18_tzadi from './gematria/letters/18-tzadi.svg'
import LETTER_19_qof from './gematria/letters/19-qof.svg'
import LETTER_20_resh from './gematria/letters/20-resh.svg'
import LETTER_21_shin from './gematria/letters/21-shin.svg'
import LETTER_22_tav from './gematria/letters/22-tav.svg'
import NAWAL_01_batz from './tzolkin/nawales/01-batz.svg'
import NAWAL_02_e from './tzolkin/nawales/02-e.svg'
import NAWAL_03_aj from './tzolkin/nawales/03-aj.svg'
import NAWAL_04_ix from './tzolkin/nawales/04-ix.svg'
import NAWAL_05_tzikin from './tzolkin/nawales/05-tzikin.svg'
import NAWAL_06_ajmaq from './tzolkin/nawales/06-ajmaq.svg'
import NAWAL_07_noj from './tzolkin/nawales/07-noj.svg'
import NAWAL_08_tijax from './tzolkin/nawales/08-tijax.svg'
import NAWAL_09_kawoq from './tzolkin/nawales/09-kawoq.svg'
import NAWAL_10_ajpu from './tzolkin/nawales/10-ajpu.svg'
import NAWAL_11_imox from './tzolkin/nawales/11-imox.svg'
import NAWAL_12_iq from './tzolkin/nawales/12-iq.svg'
import NAWAL_13_aqabal from './tzolkin/nawales/13-aqabal.svg'
import NAWAL_14_kat from './tzolkin/nawales/14-kat.svg'
import NAWAL_15_kan from './tzolkin/nawales/15-kan.svg'
import NAWAL_16_kame from './tzolkin/nawales/16-kame.svg'
import NAWAL_17_kej from './tzolkin/nawales/17-kej.svg'
import NAWAL_18_qanil from './tzolkin/nawales/18-qanil.svg'
import NAWAL_19_toj from './tzolkin/nawales/19-toj.svg'
import NAWAL_20_tzi from './tzolkin/nawales/20-tzi.svg'
import PLANET_jupiter from './astrology/planets/jupiter.svg'
import PLANET_mars from './astrology/planets/mars.svg'
import PLANET_mercury from './astrology/planets/mercury.svg'
import PLANET_moon from './astrology/planets/moon.svg'
import PLANET_neptune from './astrology/planets/neptune.svg'
import PLANET_pluto from './astrology/planets/pluto.svg'
import PLANET_saturn from './astrology/planets/saturn.svg'
import PLANET_sun from './astrology/planets/sun.svg'
import PLANET_uranus from './astrology/planets/uranus.svg'
import PLANET_venus from './astrology/planets/venus.svg'
import ELEMENT_air from './astrology/elements/air.svg'
import ELEMENT_earth from './astrology/elements/earth.svg'
import ELEMENT_fire from './astrology/elements/fire.svg'
import ELEMENT_water from './astrology/elements/water.svg'
import HD_TYPE_generator from './human-design/types/generator.svg'
import HD_TYPE_manifesting_generator from './human-design/types/manifesting-generator.svg'
import HD_TYPE_manifestor from './human-design/types/manifestor.svg'
import HD_TYPE_projector from './human-design/types/projector.svg'
import HD_TYPE_reflector from './human-design/types/reflector.svg'
import HD_CENTER_ajna_defined from './human-design/centers/ajna-defined.svg'
import HD_CENTER_ajna from './human-design/centers/ajna.svg'
import HD_CENTER_g_center_defined from './human-design/centers/g-center-defined.svg'
import HD_CENTER_g_center from './human-design/centers/g-center.svg'
import HD_CENTER_head_defined from './human-design/centers/head-defined.svg'
import HD_CENTER_head from './human-design/centers/head.svg'
import HD_CENTER_heart_defined from './human-design/centers/heart-defined.svg'
import HD_CENTER_heart from './human-design/centers/heart.svg'
import HD_CENTER_root_defined from './human-design/centers/root-defined.svg'
import HD_CENTER_root from './human-design/centers/root.svg'
import HD_CENTER_sacral_defined from './human-design/centers/sacral-defined.svg'
import HD_CENTER_sacral from './human-design/centers/sacral.svg'
import HD_CENTER_solar_plexus_defined from './human-design/centers/solar-plexus-defined.svg'
import HD_CENTER_solar_plexus from './human-design/centers/solar-plexus.svg'
import HD_CENTER_spleen_defined from './human-design/centers/spleen-defined.svg'
import HD_CENTER_spleen from './human-design/centers/spleen.svg'
import HD_CENTER_throat_defined from './human-design/centers/throat-defined.svg'
import HD_CENTER_throat from './human-design/centers/throat.svg'

export type GlyphComponent = React.FC<SvgProps>

export const SEAL_GLYPHS: Readonly<Record<number, GlyphComponent>> = {
  1: SEAL_01_dragon,
  2: SEAL_02_wind,
  3: SEAL_03_night,
  4: SEAL_04_seed,
  5: SEAL_05_serpent,
  6: SEAL_06_worldbridger,
  7: SEAL_07_hand,
  8: SEAL_08_star,
  9: SEAL_09_moon,
  10: SEAL_10_dog,
  11: SEAL_11_monkey,
  12: SEAL_12_human,
  13: SEAL_13_skywalker,
  14: SEAL_14_wizard,
  15: SEAL_15_eagle,
  16: SEAL_16_warrior,
  17: SEAL_17_earth,
  18: SEAL_18_mirror,
  19: SEAL_19_storm,
  20: SEAL_20_sun,
}

export const TONE_GLYPHS: Readonly<Record<number, GlyphComponent>> = {
  1: TONE_01_magnetic,
  2: TONE_02_lunar,
  3: TONE_03_electric,
  4: TONE_04_self_existing,
  5: TONE_05_overtone,
  6: TONE_06_rhythmic,
  7: TONE_07_resonant,
  8: TONE_08_galactic,
  9: TONE_09_solar,
  10: TONE_10_planetary,
  11: TONE_11_spectral,
  12: TONE_12_crystal,
  13: TONE_13_cosmic,
}

export const SIGN_GLYPHS: Readonly<Record<number, GlyphComponent>> = {
  1: SIGN_01_aries,
  2: SIGN_02_taurus,
  3: SIGN_03_gemini,
  4: SIGN_04_cancer,
  5: SIGN_05_leo,
  6: SIGN_06_virgo,
  7: SIGN_07_libra,
  8: SIGN_08_scorpio,
  9: SIGN_09_sagittarius,
  10: SIGN_10_capricorn,
  11: SIGN_11_aquarius,
  12: SIGN_12_pisces,
}

export const LETTER_GLYPHS: Readonly<Record<number, GlyphComponent>> = {
  1: LETTER_01_aleph,
  2: LETTER_02_bet,
  3: LETTER_03_gimel,
  4: LETTER_04_dalet,
  5: LETTER_05_he,
  6: LETTER_06_vav,
  7: LETTER_07_zayin,
  8: LETTER_08_chet,
  9: LETTER_09_tet,
  10: LETTER_10_yod,
  11: LETTER_11_kaf,
  12: LETTER_12_lamed,
  13: LETTER_13_mem,
  14: LETTER_14_nun,
  15: LETTER_15_samech,
  16: LETTER_16_ayin,
  17: LETTER_17_pe,
  18: LETTER_18_tzadi,
  19: LETTER_19_qof,
  20: LETTER_20_resh,
  21: LETTER_21_shin,
  22: LETTER_22_tav,
}

export const NAWAL_GLYPHS: Readonly<Record<string, GlyphComponent>> = {
  'batz': NAWAL_01_batz,
  'e': NAWAL_02_e,
  'aj': NAWAL_03_aj,
  'ix': NAWAL_04_ix,
  'tzikin': NAWAL_05_tzikin,
  'ajmaq': NAWAL_06_ajmaq,
  'noj': NAWAL_07_noj,
  'tijax': NAWAL_08_tijax,
  'kawoq': NAWAL_09_kawoq,
  'ajpu': NAWAL_10_ajpu,
  'imox': NAWAL_11_imox,
  'iq': NAWAL_12_iq,
  'aqabal': NAWAL_13_aqabal,
  'kat': NAWAL_14_kat,
  'kan': NAWAL_15_kan,
  'kame': NAWAL_16_kame,
  'kej': NAWAL_17_kej,
  'qanil': NAWAL_18_qanil,
  'toj': NAWAL_19_toj,
  'tzi': NAWAL_20_tzi,
}

export const PLANET_GLYPHS: Readonly<Record<string, GlyphComponent>> = {
  'jupiter': PLANET_jupiter,
  'mars': PLANET_mars,
  'mercury': PLANET_mercury,
  'moon': PLANET_moon,
  'neptune': PLANET_neptune,
  'pluto': PLANET_pluto,
  'saturn': PLANET_saturn,
  'sun': PLANET_sun,
  'uranus': PLANET_uranus,
  'venus': PLANET_venus,
}

export const ELEMENT_GLYPHS: Readonly<Record<string, GlyphComponent>> = {
  'air': ELEMENT_air,
  'earth': ELEMENT_earth,
  'fire': ELEMENT_fire,
  'water': ELEMENT_water,
}

export const HD_TYPE_GLYPHS: Readonly<Record<string, GlyphComponent>> = {
  'generator': HD_TYPE_generator,
  'manifesting-generator': HD_TYPE_manifesting_generator,
  'manifestor': HD_TYPE_manifestor,
  'projector': HD_TYPE_projector,
  'reflector': HD_TYPE_reflector,
}

export const HD_CENTER_GLYPHS: Readonly<
  Record<string, { base: GlyphComponent; defined: GlyphComponent }>
> = {
  'ajna': { base: HD_CENTER_ajna, defined: HD_CENTER_ajna_defined },
  'g-center': { base: HD_CENTER_g_center, defined: HD_CENTER_g_center_defined },
  'head': { base: HD_CENTER_head, defined: HD_CENTER_head_defined },
  'heart': { base: HD_CENTER_heart, defined: HD_CENTER_heart_defined },
  'root': { base: HD_CENTER_root, defined: HD_CENTER_root_defined },
  'sacral': { base: HD_CENTER_sacral, defined: HD_CENTER_sacral_defined },
  'solar-plexus': { base: HD_CENTER_solar_plexus, defined: HD_CENTER_solar_plexus_defined },
  'spleen': { base: HD_CENTER_spleen, defined: HD_CENTER_spleen_defined },
  'throat': { base: HD_CENTER_throat, defined: HD_CENTER_throat_defined },
}
