export type { ColorFamily } from './common'
export type { Seal } from './seal'
export type { Tone } from './tone'
export type { DreamspellKin, Oracle } from './dreamspell'
export type { TzolkinDaySign, TzolkinDay } from './tzolkin'
export type { Person, ComputedPerson } from './person'
export type {
  RelationshipType,
  FamilySubtype,
  RomanticSubtype,
  FriendSubtype,
  ProfessionalSubtype,
  RelationshipSubtype,
  RelationshipStrength,
  RelationshipWithPeople,
  RelationshipFromPerson,
  GraphNode,
  GraphEdge,
  GraphCluster,
  RelationshipGraph,
  RawGraphData,
  GroupPreset,
  GroupWithMembers,
  HarmonyType,
  DreamspellConnection,
  DreamspellCompatibility,
  CompatibilityMatrixEntry,
  CompatibilityMatrix,
  GroupAnalysis,
  ShareOptions,
  ShareLink,
  CreateRelationshipInput,
  UpdateRelationshipInput,
  CreateGroupInput,
  UpdateGroupInput,
  CreateShareInput,
} from './relationship'
export {
  RELATIONSHIP_SUBTYPES,
  RELATIONSHIP_TYPE_LABELS,
  STRENGTH_LABELS,
} from './relationship'

// Phase 3.3: Astrology types
export type {
  Element,
  Modality,
  PlanetType,
  PlanetId,
  ZodiacSignId,
  AspectNature,
  Dignity,
  ChartShape,
  HouseSystem,
  ZodiacType,
  ZodiacSign,
  Planet,
  House,
  Aspect,
  ZodiacPosition,
  PlanetPosition,
  HousePosition,
  AspectInstance,
  BirthPlace,
  NatalChart,
  SunSignChart,
  AstrologyInput,
  Transit,
  TransitReport,
  InterAspect,
  SynastryReport,
} from './astrology'
export {
  ELEMENT_LABELS,
  MODALITY_LABELS,
  HOUSE_SYSTEM_LABELS,
} from './astrology'

// Phase 3.4: Human Design types
export type {
  CenterId,
  HumanDesignType,
  Authority,
  ProfileLine,
  Circuitry,
  Definition,
  Quarter,
  HumanDesignPlanet,
  Center,
  CenterState,
  Gate,
  Channel,
  Profile,
  TypeDefinition,
  AuthorityDefinition,
  IncarnationCross,
  HumanDesignInput,
  PlanetaryActivation,
  ActivationSet,
  Bodygraph,
  PartialBodygraph,
  HumanDesignResult,
  ConnectionType,
  CompositeAnalysis,
} from './human-design'
export {
  TYPE_LABELS,
  TYPE_LABELS_HEBREW,
  AUTHORITY_LABELS,
  AUTHORITY_LABELS_HEBREW,
  CENTER_LABELS,
  CENTER_LABELS_HEBREW,
  DEFINITION_LABELS,
  DEFINITION_LABELS_HEBREW,
  CIRCUITRY_LABELS,
  CIRCUITRY_LABELS_HEBREW,
  QUARTER_LABELS,
  QUARTER_LABELS_HEBREW,
} from './human-design'

// Phase 3.5: Gematria types
export type {
  HebrewLetterId,
  FinalLetterId,
  AllHebrewLetterId,
  GematriaMethod,
  HebrewLetter,
  LetterBreakdown,
  GematriaValue,
  GematriaResult,
  NameGematria,
  NameComparison,
  GroupGematria,
  NotableNumber,
  PersonGematria,
} from './gematria'
export {
  GEMATRIA_METHOD_LABELS,
  DIGITAL_ROOT_LABELS,
} from './gematria'

// Phase 4: Canvas Editor / Board types
export type {
  BoardTemplate,
  BoardId,
  NodeId,
  ConnectionId,
  LayerId,
  ViewBox,
  Background,
  GridSettings,
  CanvasState,
  Layer,
  Position,
  Size,
  ShadowStyle,
  BorderStyle,
  NodeStyle,
  PersonDisplayMode,
  SystemType,
  PersonNode,
  CardVariant,
  CardNode,
  ChartType,
  ChartData,
  ChartNode,
  TextStyle,
  TextNode,
  ImageNode,
  ShapeType,
  FillStyle,
  StrokeStyle,
  ShapeNode,
  GroupNode,
  CanvasNode,
  ConnectionType as CanvasConnectionType,
  Anchor,
  Marker,
  ConnectionStyle,
  CanvasConnection,
  StickyColor,
  StickyNote,
  Highlight,
  Callout,
  Freehand,
  Annotation,
  ToolId,
  Tool,
  SelectionBox,
  TransformHandle,
  SelectionState,
  DragState,
  HistoryState,
  ExportFormat,
  ExportOptions,
  PDFExportOptions,
  CreateBoardInput,
  UpdateBoardInput,
  CreateBoardShareInput,
  BoardWithStats,
  BoardShareWithUrl,
} from './board'
export {
  BOARD_TEMPLATES,
  DEFAULT_CANVAS_STATE,
  DEFAULT_LAYERS,
  SYSTEM_LAYERS,
  STICKY_COLORS,
  TOOLS,
} from './board'

// Phase 3.2: Prediction system types
export type {
  PredictionSystem,
  PredictionType,
  PredictionIntensity,
  PredictionEvent,
  PredictionEventData,
  DailyPrediction,
  WeeklyPrediction,
  MonthlyPrediction,
  PersonalTimeline,
  TimelineMilestone,
  GalacticReturnMilestone,
  TunBirthdayMilestone,
  KatunBirthdayMilestone,
  CalendarRoundMilestone,
  NotificationChannel,
  NotificationSettings,
  CalendarEvent,
  ICSEvent,
  AIInterpretationRequest,
  AIInterpretationResponse,
  PredictionAPIResponse,
  DailyPredictionResponse,
  WeeklyPredictionResponse,
  MonthlyPredictionResponse,
  TimelineResponse,
} from './prediction'
export {
  INTENSITY_WEIGHTS,
  DEFAULT_NOTIFICATION_SETTINGS,
  calculateIntensity,
} from './prediction'
