// @ts-check
/**
 * Glyph registry generator.
 *
 * Reads the SVG glyph sets under assets/glyphs/** (potrace monochrome, painted
 * fill="currentColor" so they tint to any theme colour) and emits a typed
 * registry that maps each reading's own key onto its glyph component.
 *
 * Generated, never authored — same contract as generate-m3-palette.mjs. To add
 * or replace a glyph, drop the SVG in the right set folder and re-run:
 *   node scripts/generate-glyphs.mjs
 *
 * Metro's react-native-svg-transformer turns each `import X from './x.svg'`
 * into a react-native-svg component; the `color` prop drives currentColor.
 */
import { readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const GLYPH_ROOT = join(HERE, '..', 'assets', 'glyphs')
const OUT = join(GLYPH_ROOT, 'glyphs.gen.ts')

/**
 * Each set names its folder, the exported map, and how a file's basename
 * becomes the map key:
 *   'number' — leading NN- is the semantic index (seal 1-20, tone 1-13, …)
 *   'slug'   — the name after NN- is the key (nawal Kʼicheʼ day-sign slugs)
 *   'base'   — the whole basename is the key (planets, elements, HD types)
 *   'center' — HD centres: `<slug>` and `<slug>-defined` fold into one entry
 * @type {Array<{ dir: string, export: string, key: 'number'|'slug'|'base'|'center' }>}
 */
const SETS = [
  { dir: 'dreamspell/seals', export: 'SEAL_GLYPHS', key: 'number' },
  { dir: 'dreamspell/tones', export: 'TONE_GLYPHS', key: 'number' },
  { dir: 'astrology/signs', export: 'SIGN_GLYPHS', key: 'number' },
  { dir: 'gematria/letters', export: 'LETTER_GLYPHS', key: 'number' },
  { dir: 'tzolkin/nawales', export: 'NAWAL_GLYPHS', key: 'slug' },
  { dir: 'astrology/planets', export: 'PLANET_GLYPHS', key: 'base' },
  { dir: 'astrology/elements', export: 'ELEMENT_GLYPHS', key: 'base' },
  { dir: 'human-design/types', export: 'HD_TYPE_GLYPHS', key: 'base' },
  { dir: 'human-design/centers', export: 'HD_CENTER_GLYPHS', key: 'center' },
]

/** A file's basename with the .svg extension dropped. */
const stem = (file) => file.replace(/\.svg$/, '')
/** The name part after an optional NN- ordinal prefix. */
const slugOf = (file) => stem(file).replace(/^\d+-/, '')
/** A collision-free JS identifier for an import binding. */
const identOf = (setToken, file) =>
  `${setToken}_${stem(file).replace(/[^a-zA-Z0-9]/g, '_')}`

const imports = []
const blocks = []

for (const set of SETS) {
  const files = readdirSync(join(GLYPH_ROOT, set.dir))
    .filter((f) => f.endsWith('.svg'))
    .sort()
  const setToken = set.export.replace(/_GLYPHS$/, '')

  for (const file of files) {
    imports.push(`import ${identOf(setToken, file)} from './${set.dir}/${file}'`)
  }

  if (set.key === 'center') {
    // Group `ajna` + `ajna-defined` into { base, defined } per centre.
    const centres = new Map()
    for (const file of files) {
      const s = stem(file)
      const defined = s.endsWith('-defined')
      const name = defined ? s.replace(/-defined$/, '') : s
      const entry = centres.get(name) ?? {}
      entry[defined ? 'defined' : 'base'] = identOf(setToken, file)
      centres.set(name, entry)
    }
    const rows = [...centres.entries()].map(
      ([name, e]) => `  '${name}': { base: ${e.base}, defined: ${e.defined} },`
    )
    blocks.push(
      `export const ${set.export}: Readonly<\n` +
        `  Record<string, { base: GlyphComponent; defined: GlyphComponent }>\n` +
        `> = {\n${rows.join('\n')}\n}`
    )
    continue
  }

  const rows = files.map((file) => {
    const ident = identOf(setToken, file)
    if (set.key === 'number') return `  ${parseInt(file, 10)}: ${ident},`
    const key = set.key === 'slug' ? slugOf(file) : stem(file)
    return `  '${key}': ${ident},`
  })
  const keyType = set.key === 'number' ? 'number' : 'string'
  blocks.push(
    `export const ${set.export}: Readonly<Record<${keyType}, GlyphComponent>> = {\n` +
      `${rows.join('\n')}\n}`
  )
}

const header = `// AUTO-GENERATED by scripts/generate-glyphs.mjs — DO NOT EDIT.
// Source: assets/glyphs/** (potrace monochrome, fill="currentColor").
// Regenerate: node scripts/generate-glyphs.mjs
import type React from 'react'
import type { SvgProps } from 'react-native-svg'
${imports.join('\n')}

export type GlyphComponent = React.FC<SvgProps>
`

writeFileSync(OUT, `${header}\n${blocks.join('\n\n')}\n`)
console.log(`glyphs.gen.ts — ${imports.length} glyphs across ${SETS.length} sets`)
